# Generated by Django 2.2.16 on 2022-07-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='başlıq')),
                ('context', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Haqqımızda',
            },
        ),
        migrations.CreateModel(
            name='AskQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='ad')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='poçt ünvanı')),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='tel')),
                ('question', models.TextField(blank=True, null=True, verbose_name='soruşulan sual')),
            ],
            options={
                'verbose_name_plural': 'Soruşulan suallar',
            },
        ),
        migrations.CreateModel(
            name='OurTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(upload_to='profile/')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='ad')),
                ('surname', models.CharField(blank=True, max_length=200, null=True, verbose_name='soyad')),
                ('position', models.CharField(blank=True, max_length=200, null=True, verbose_name='vəzifə')),
            ],
            options={
                'verbose_name_plural': 'Komandamızın üzvləri',
            },
        ),
        migrations.CreateModel(
            name='RequestPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='ad')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='poçt ünvanı')),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='tel')),
                ('message', models.TextField(blank=True, null=True, verbose_name='mesaj')),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=400, null=True, verbose_name='başlıq')),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='slide/')),
            ],
        ),
        migrations.CreateModel(
            name='WriteDirector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='ad')),
                ('company_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='müəssisə adı')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='poçt ünvanı')),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='tel')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='şəhər')),
                ('question', models.TextField(blank=True, null=True, verbose_name='context')),
            ],
            options={
                'verbose_name_plural': 'Direktora yazılanlar',
            },
        ),
    ]
