# Generated by Django 2.2.16 on 2022-07-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(blank=True, max_length=300, null=True, verbose_name='istifadəçi adı')),
                ('surname', models.CharField(blank=True, max_length=300, null=True, verbose_name='istifadəçi soyadı')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='istifadəçi ünvanı')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='poçt ünvanı')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='tel')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
